version: "0.1"
syncs:
  - id: bcdd2992-695d-4a25-af37-0adb67796615
    connection_id: 43394a49-6ff9-4713-bd4a-7b7cf627513c
    name: another sync
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: blns_dataset_uid
        target_name: blns_dataset
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: blns_dataset_uid.blns_col
            target_name: blns_col
