version: "0.1"
syncs:
  - id: 49efd397-9b90-4a79-9bf2-3ff937ad8327
    connection_id: 594c6c2f-7715-4089-b7b4-8cdf6192c617
    name: asdf
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: biomarkers-30600-both_sexes-irnt
        target_name: biomarkers_30600_both_sexes_irnt
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: biomarkers-30600-both_sexes-irnt.af_AFR
            target_name: af_afr
