version: "0.1"
syncs:
  - id: 765df850-1c26-403a-a101-d7906e7ca043
    connection_id: 0debd888-9a65-44bb-aa4e-c75b6c4ab244
    name: dig
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: dataset_with_deletes_uid
        target_name: dataset_with_deletes
        data_extraction_config:
          name: Incremental
          values:
            percent_deletes: "0.1"
            random_deletes: true
        loading_option:
          type: Upsert
          delete_mode: soft
          primary_keys:
            - dataset_with_deletes_uid.id
        data_fields:
          - unique_id: dataset_with_deletes_uid.id
            target_name: id
          - unique_id: dataset_with_deletes_uid.val
            target_name: val
