version: "0.1"
syncs:
  - id: 8d0715f8-3015-499e-a021-a92c09cca74c
    connection_id: 15546d63-a3ca-4fab-b6d8-5a2b5c204412
    name: fdg
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: dataset_with_deletes_uid
        target_name: dataset_with_deletes
        data_extraction_config:
          name: Incremental
          values:
            random_deletes: true
            percent_deletes: "0.1"
        loading_option:
          type: Upsert
          delete_mode: soft
          primary_keys:
            - dataset_with_deletes_uid.id
        data_fields:
          - unique_id: dataset_with_deletes_uid.id
            target_name: id
          - unique_id: dataset_with_deletes_uid.val
            target_name: val
