version: "0.1"
syncs:
  - id: 5f0c6943-cd61-4afc-b3ec-4e759187b6aa
    connection_id: 6778f0ab-e81b-4dc7-afc6-c0d95dfc7096
    name: pg_sync
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: demo.source.products
        target_name: products
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: demo.source.products.productstyle
            target_name: productstyle
          - unique_id: demo.source.products.productsubcategorykey
            target_name: productsubcategorykey
          - unique_id: demo.source.products.productcolor
            target_name: productcolor
          - unique_id: demo.source.products.productname
            target_name: productname
          - unique_id: demo.source.products.productdescription
            target_name: productdescription
          - unique_id: demo.source.products.productcost
            target_name: productcost
          - unique_id: demo.source.products.productsize
            target_name: productsize
          - unique_id: demo.source.products.productprice
            target_name: productprice
          - unique_id: demo.source.products.modelname
            target_name: modelname
          - unique_id: demo.source.products.productsku
            target_name: productsku
          - unique_id: demo.source.products.productkey
            target_name: productkey
