version: "0.1"
syncs:
  - id: 0c509cd1-6c3b-4780-b23b-efaed0e672b2
    connection_id: 6778f0ab-e81b-4dc7-afc6-c0d95dfc7096
    name: pg_sync
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        compression: zstd
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: demo.source.products
        target_name: products
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Upsert
          delete_mode: hard
          primary_keys:
            - demo.source.products.productkey
        data_fields:
          - unique_id: demo.source.products.modelname
            target_name: modelname
          - unique_id: demo.source.products.productkey
            target_name: productkey
