version: "0.1"
syncs:
  - id: b188fb52-bbac-401f-b574-a1865c0c47f1
    connection_id: b8fdd3d1-6485-4b64-9054-97c85345557e
    name: sadf
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: blns_dataset_uid
        target_name: blns_dataset
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: blns_dataset_uid.blns_col
            target_name: blns_col
