version: "0.1"
syncs:
  - id: 00a61262-9bfb-498b-8a73-ca766790e302
    connection_id: 498efe31-6c7c-499c-857b-8f3b7b9b6897
    name: sync
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: blns_dataset_uid
        target_name: blns_dataset
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: blns_dataset_uid.blns_col
            target_name: blns_col
