version: "0.1"
syncs:
  - id: cd2aaaf2-bfd5-42c4-b948-891f3708d9ac
    connection_id: 99d69ac8-fd04-4cc3-b0d8-cad5d6aba57a
    name: sync
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: dataset_with_deletes_uid
        target_name: dataset_with_deletes
        data_extraction_config:
          name: Incremental
          values:
            percent_deletes: "0.1"
            random_deletes: true
        loading_option:
          type: Upsert
          delete_mode: soft
          primary_keys:
            - dataset_with_deletes_uid.id
        data_fields:
          - unique_id: dataset_with_deletes_uid.id
            target_name: id
          - unique_id: dataset_with_deletes_uid.val
            target_name: val
      - unique_id: dataset_with_one_absurdly_big_record
        target_name: dataset_with_one_absurdly_big_record
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: dataset_with_one_absurdly_big_record.id
            target_name: id
          - unique_id: dataset_with_one_absurdly_big_record.val
            target_name: val
      - unique_id: dummy_contacts_uid
        target_name: dummy_contacts
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: dummy_contacts_uid.company
            target_name: company
          - unique_id: dummy_contacts_uid.email
            target_name: email
          - unique_id: dummy_contacts_uid.name
            target_name: name
