version: "0.1"
syncs:
  - id: 71e2532b-605f-4c6b-a8d8-9febba7cae34
    connection_id: 5808ecfa-4deb-4ae4-95db-ec296a976beb
    name: sync
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: dummy_contacts_uid
        target_name: dummy_contacts
        data_extraction_config:
          name: Full Extract
        loading_option:
          type: Upsert
          delete_mode: hard
          primary_keys:
            - dummy_contacts_uid.company
        data_fields:
          - unique_id: dummy_contacts_uid.company
            target_name: company
