version: "0.1"
syncs:
  - id: ab83942f-1ffb-4a08-8584-e784f6faf4bf
    connection_id: daa35cca-d42f-43fa-9183-f1ce3429a50b
    name: sync 2
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        compression: zstd
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: blns_dataset_uid
        target_name: blns_dataset_1
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: blns_dataset_uid.blns_col
            target_name: blns_col
