version: "0.1"
syncs:
  - id: 831955c2-5664-4429-b0cc-ec08f738ef80
    connection_id: a70aff7e-d282-411b-9468-c3469deee944
    name: sync
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        compression: zstd
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: dataset
        target_name: dataset
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: dataset.any
            target_name: any
          - unique_id: dataset.array_any
            target_name: array_any
      - unique_id: dataset_with_deletes_uid
        target_name: dataset_with_deletes
        data_extraction_config:
          name: Incremental
          values:
            random_deletes: true
            percent_deletes: "0.1"
        loading_option:
          type: Upsert
          delete_mode: soft
          primary_keys:
            - dataset_with_deletes_uid.id
        data_fields:
          - unique_id: dataset_with_deletes_uid.id
            target_name: id
          - unique_id: dataset_with_deletes_uid.val
            target_name: val
