version: "0.1"
syncs:
  - id: d6334719-6393-4164-a2c0-2ce94bdec0bd
    connection_id: f2893cfa-38bd-4600-a456-d662c8a1edb6
    name: sync
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: dummy_contacts_uid
        target_name: dummy_contacts
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Upsert
          delete_mode: hard
          primary_keys:
            - dummy_contacts_uid.company
        data_fields:
          - unique_id: dummy_contacts_uid.company
            target_name: company
          - unique_id: dummy_contacts_uid.email
            target_name: email
          - unique_id: dummy_contacts_uid.name
            target_name: name
