version: "0.1"
syncs:
  - id: 7d85576c-0ec4-4e20-b5b4-e84f64e2884d
    connection_id: 3b70f19e-be0e-4617-8f91-ddcaca94eb6b
    name: sync
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        compression: zstd
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: dataset_with_one_absurdly_big_record
        target_name: new_name
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: dataset_with_one_absurdly_big_record.id
            target_name: id
      - unique_id: dataset
        target_name: dataset
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: dataset.any
            target_name: any
          - unique_id: dataset.array_any
            target_name: array_any
          - unique_id: dataset.array_boolean
            target_name: array_boolean
